ItemNames:
	db "Master Ball@"
	db "Ultra Ball@"
	db "Great Ball@"
	db "Poké Ball@"
	db "Town Map@"
	db "Bicycle@"
	db "Surfboard@" ;joenote - give the surfboard it's fan name instead of ?????
	db "Safari Ball@"
	db "Pokédex@"
	db "Moon Stone@"
	db "Antidote@"
	db "Burn Heal@"
	db "Ice Heal@"
	db "Awakening@"
	db "Parlyz Heal@"
	db "Full Restore@"
	db "Max Potion@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "Boulder Badge@"
	db "Cascade Badge@"
	db "Thunder Badge@"
	db "Rainbow Badge@"
	db "Soul Badge@"
	db "Marsh Badge@"
	db "Volcano Badge@"
	db "Earth Badge@"
	db "Escape Rope@"
	db "Repel@"
	db "Old Amber@"
	db "Fire Stone@"
	db "Thunderstone@"
	db "Water Stone@"
	db "Hp Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "Rare Candy@"
	db "Dome Fossil@"
	db "Helix Fossil@"
	db "Secret Key@"
	db "Mist Stone@"
	db "Bike Voucher@"
	db "X Accuracy@"
	db "Leaf Stone@"
	db "Card Key@"
	db "Nugget@"
	db "M.Gene@"
	db "Poké Doll@"
	db "Full Heal@"
	db "Revive@"
	db "Max Revive@"
	db "Guard Spec.@"
	db "Super Repel@"
	db "Max Repel@"
	db "Dire Hit@"
	db "Coin@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "S.S.Ticket@"
	db "Gold Teeth@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Special@"
	db "Coin Case@"
	db "Oak's Parcel@"
	db "Itemfinder@"
	db "Silph Scope@"
	db "Poké Flute@"
	db "Lift Key@"
	db "Exp.All@"
	db "Old Rod@"
	db "Good Rod@"
	db "Super Rod@"
	db "Pp Up@"
	db "Ether@"
	db "Max Ether@"
	db "Elixer@"
	db "Max Elixer@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
	db "Metal Coat@" ;dafthunk #19
	db "Exp Booster@"
	